name: flutter_tem
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.7.2
  dio: ^5.8.0+1
  flutter_screenutil: ^5.9.3
  flutter_dotenv: ^5.2.1
  flutter_easyloading: ^3.0.5
  shared_preferences: 2.3.2
  jpush_flutter: 3.2.0 #推送
  webview_flutter: ^4.10.0
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
    - .env.development
    - .env.test
    - .env.production

  uses-material-design: true


